### ISSUE TITLE
Reduce nested function definitions via @tf.function

### ISSUE THREAD

**Issue by aaronmondal** [tensorflow/addons#2279]
As already discussed, in #2264 there are some inconsistencies with the usage of `@tf.function` and undesirable nested functions which may cleaned up by using `@tf.function`.

After running `grep -r -n "tf.function" .`, removing `test` files and `README` files I found the following:

```bash
./text/crf.py
```
This file was already addressed in #598 by @seanpmorgan, but the PR was closed because it was unclear how to handle variable shapes (which seem kind of necessary for text data :D). Looser shape constraints using explicit `input_signature`s in `@tf.function` may be a simple way to improve performance while staying flexible. **Note** that using looser shape constraints may result in slower execution than when using static shapes as pointed out by @fsx950223 [here](https://github.com/tensorflow/addons/pull/2264#issuecomment-740428815). I expect this would still be faster than no decoration at all.

```bash
./metrics/cohens_kappa.py
```
This file is rather inconsistent. Some functions are decorated, others are not. I assume a refactorization will lead to increased readability/maintainability and `@tf.function` decorations at the top level should give a nice performance gain.

```bash
./image/connected_components.py
```
This uses `tf.cond` internally. As far as I understand, `if` statements are translated to `tf.cond` anyways, provided that the condition is a `tf.Tensor` and the branches are compatible (see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/control_flow.md#if-statements)). Changing this to a regular `if` statement may therefore improve readability. It may also make it possible to get rid of the nested function definitions in this file.
```bash
./image/color_ops.py
```
While `equalize` was refactored in #2264, `sharpness` is currently undecorated. Decorating may lead to a nice performance improvement.

```bash
./image/translate_ops.py
```
While `translate` is decorated, `translate_xy` is not. Since `translate_xy` makes use of `translate` internally, my assumption is that `translate` will excessively retrace in some cases, while `translate_xy` on its own is rather slow since it is untraced when used via the public API.

### `tf.cond` and `tf.while`
After checking the outputs of `grep -r -n "tf.cond" .` I noticed the following:

```bash
./layers/wrappers.py
./seq2seq/sampler.py
./seq2seq/beam_search_decoder.py
./optimizers/novograd.py
```
These use `tf.cond`. With `tf.function` we may be able to get rid of the nested function definitions and improve readability.

Finally, `grep -r -n "tf.while" .` returned `./seq2seq/decoder.py` which also makes use of `tensorflow.python.ops.control_flow_util`. This already contains a `TODO` stating an alternative implementation would be desirable.

It may not be possible to get rid of *all* `tf.cond` statements as `tf.function` cannot convert *every* python `if` to `tf.cond` ([link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/control_flow.md#if-statements)).

These `grep`s do *not* include code which is currently not decorated at all, but I think the above mentioned files would be a good starting point. I will address the mentioned issues as fast as I can, but most of the suggested changes will require some time to benchmark in order to avoid performance regression.

---

Pulling in @WindQAQ @bhack and @AakashKumarNain who already were part of the previous discussion.

Linking issue #13 as it contains another discussion about `tf.funcion`.

### TODOS:

- [ ] [`./image/connected_components.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/connected_components.py)
- [ ] [`./image/color_ops.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/color_ops.py)
- [ ] [`./image/translate_ops.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/translate_ops.py)
- [ ] [`./layers/wrappers.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/wrappers.py)
- [ ] [`./metrics/cohens_kappa.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/cohens_kappa.py)
- [ ] [`./optimizers/novograd.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/novograd.py)
- [ ] [`./seq2seq/sampler.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/sampler.py)
- [ ] [`./seq2seq/beam_search_decoder.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/beam_search_decoder.py)
- [ ] [`./seq2seq/decoder.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/decoder.py)
- [ ] [`./text/crf.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/crf.py)

**Comment by WindQAQ** [comment]
Acutally, I'm not a fan of aggressively decorating `@tf.function` in the library in any reason. Users should decide whether to use it or not. Abuse of `tf.function` can cause excessive graph retracing. At least, we should do benchmarks and decorate it for performance.

**Comment by aaronmondal** [comment]
> Abuse of `tf.function` can cause excessive graph retracing. At least, we should do benchmarks and decorate it for performance. Or use it if there is any other special case such as the function is used for tflite conversion.

Absolutely agreed! Nothing should be decorated without thought and benchmarks are necessary before changing anything. There is no point in decorating things without reason.

> Acutally, I'm not a fan of aggressively decorating `@tf.function` in the library in any reason. Users should decide whether to use it or not.

The two consistent choices in my opinion would be:
1. Not using `tf.function` in TFA. This would require users to use e.g.
    ```python
    functionized = tf.function(tfa.some_function)
    functionized(inputs)
    ```
    to **enable** tracing.
2.  Using `tf.function` in TFA. This would require users to use e.g.
    ```python
    tf.config.run_functions_eagerly(True)
    tfa.some_function(inputs)
    tf.config.run_functions_eagerly(False)
    ```
    to **disable** tracing.

As far as I understand using `tf.function` wherever possible was the consensus reached in #13. Most of the public API functions in TFA are already decorated as well. My issue is that not having consistency in the public API requires always checking the source for every TFA method that is used as a standalone which is quite tedious.

**Comment by aaronmondal** [comment]
Oh and actually retracing should not be an issue as it can easily be suppressed by specifying `input_shape`:
```python
@tf.function
def func_1(tensor, integer):
    print('Tracing func_1.')
    return tensor + integer

@tf.function(
    input_signature=(tf.TensorSpec([]), tf.TensorSpec([]))
)
def func_2(tensor, integer):
    print('Tracing func_2.')
    return tensor + integer

def test_retracing(fn):
    print(f"Running test for {fn.__name__}")
    inp = tf.constant(0.0)
    for i in range(5):
        x = fn(inp, i)

test_retracing(func_1)
test_retracing(func_2)

```

```bash
Running test for func_1
Tracing func_1.
Tracing func_1.
Tracing func_1.
Tracing func_1.
Tracing func_1.
[Prints a warning about excessive retracing of func_1]
Running test for func_2
Tracing func_2.  # No warning here, only tracing once.
```

**Comment by aaronmondal** [comment]
Closing due to limited enthusiasm from the community :D We can always handle the mentioned files at a later point in time.
