### ISSUE TITLE
Addons 1.x Roadmap

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2435]
Opening this to start discussion on what core issues we need to address before considering bumping the major version of Addons to 1.x. There is no requirement to do this within any timeline, and if we feel that the repository is not ready then it is my strong belief that it's better to stay as a 0.x given the implied semantics of a semver increase.

## Requirements:

- [ ] Remove all private TF APIs as seen in the allow lists of source_contron_tests https://github.com/tensorflow/addons/issues/1735
- [ ] Make optimizer wrappers consistant https://github.com/tensorflow/addons/issues/2187
- [ ] Ensure serialization compatibility for all Addons. https://github.com/tensorflow/addons/issues/1747 addresses the optimizers.
- [ ] Unify any duplication functions across the ecosystem. As https://github.com/tensorflow/addons/issues/2384 mentions if there is duplication we should try our best to unify them
- [ ] Monitor the health of our maintainers. PR prototype https://github.com/tensorflow/addons/pull/2024

## Nice to Haves:

- [ ] Unified sub-package testing https://github.com/tensorflow/addons/issues/992
- [ ] Align typing with exported TF types https://github.com/tensorflow/addons/issues/1997

We should update this list accordingly with any other requirements / nice to haves.

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
